<a href="https://colab.research.google.com/github/Ted-star7/Images/blob/main/Images_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import json
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Load dataset
file_path = '/content/drive/MyDrive/Dataset/Uzapoint_Master_Clean_Data.csv'
df = pd.read_csv(file_path)

# Preview dataset
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Product ID,Product Label,Clean_Product_Label,Category,Subcategory,Parent_Category,Category_norm,Subcategory_norm,Volume,Brand,Product Image,needs_review,has_image,data_quality_score
0,8782,Brown Belt,Brown Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BROWN,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
1,8783,Black Belt,Black Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BLACK,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
2,8785,Apple Watch 2020,Apple Watch 2020,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
3,8797,Apple Watch 2019,Apple Watch 2019,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
4,115430,ORAIMO TYPE C DATA CABLE,ORAIMO TYPE C DATA CABLE,ACCESSORIES,PHONE CHARGERS,Still_Other,accessories,phone chargers,Unknown,ORAIMO,NaN,True,False,Needs Review

In [5]:
image_df = df[['Product ID', 'Product Image']].copy()

image_df.head()

   Product ID                                      Product Image
0        8782  https://uzapointerp.uzahost.com/uploads/produc...
1        8783  https://uzapointerp.uzahost.com/uploads/produc...
2        8785  https://uzapointerp.uzahost.com/uploads/produc...
3        8797  https://uzapointerp.uzahost.com/uploads/produc...
4      115430                                                NaN

In [6]:
missing_mask = image_df['Product Image'].isna() | (image_df['Product Image'] == "")

missing_count = missing_mask.sum()
total_products = len(image_df)

print("Total Products:", total_products)
print("Missing Images:", missing_count)
print("Existing Images:", total_products - missing_count)

Total Products: 47944
Missing Images: 39967
Existing Images: 7977

In [7]:
missing_images_df = image_df[missing_mask]

missing_images_df.head()

   Product ID Product Image
4      115430           NaN
5      115431           NaN
6      115432           NaN
7      115433           NaN
8      119107           NaN

In [8]:
import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Dataset/category_review_simple_20260303_195522/category_review_simple_20260303_195522"

import os
files = os.listdir(folder_path)

files

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

['Tobacco_simple.csv',
 'Non-Alcoholic_simple.csv',
 'Wines_simple.csv',
 'Others_simple.csv',
 'Beers_simple.csv',
 'Spirits_simple.csv']

In [9]:
import pandas as pd
import os

dfs = []

for file in files:

    path = os.path.join(folder_path, file)

    df_temp = pd.read_csv(path)

    dfs.append(df_temp)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.head()

   Product ID Category POS_Subcategory             Product Label
0      223308  Tobacco      Cigarettes               BIC LIGHTER
1      113125  Tobacco      Cigarettes  CIGAR DUNHILL DOUBLE PKT
2      113126  Tobacco      Cigarettes  CIGAR DUNHILL SINGLE PKT
3      113127  Tobacco      Cigarettes   CIGAR EMBASSY KINGS PKT
4      113128  Tobacco      Cigarettes              CIGAR SM PKT

In [10]:
print("Total Products:", len(combined_df))

Total Products: 47944

In [11]:
combined_df['Category'].value_counts()

Category
Spirits          21473
Wines             8502
Others            7556
Non-Alcoholic     5406
Beers             3984
Tobacco           1023
Name: count, dtype: int64

In [12]:
combined_df.to_csv(
"/content/drive/MyDrive/Dataset/Uzapoint_POS_Taxonomy_Base.csv",
index=False
)

In [13]:
combined_df['POS_Subcategory'].nunique()

52

In [14]:
combined_df.columns

Index(['Product ID', 'Category', 'POS_Subcategory', 'Product Label'], dtype='object')

In [15]:
image_df = image_df[['Product ID', 'Product Image']]

In [16]:
image_df.head()

   Product ID                                      Product Image
0        8782  https://uzapointerp.uzahost.com/uploads/produc...
1        8783  https://uzapointerp.uzahost.com/uploads/produc...
2        8785  https://uzapointerp.uzahost.com/uploads/produc...
3        8797  https://uzapointerp.uzahost.com/uploads/produc...
4      115430                                                NaN

In [17]:
final_df = combined_df.merge(
    image_df,
    on="Product ID",
    how="left"
)

final_df.head()

   Product ID Category POS_Subcategory             Product Label Product Image
0      223308  Tobacco      Cigarettes               BIC LIGHTER           NaN
1      113125  Tobacco      Cigarettes  CIGAR DUNHILL DOUBLE PKT           NaN
2      113126  Tobacco      Cigarettes  CIGAR DUNHILL SINGLE PKT           NaN
3      113127  Tobacco      Cigarettes   CIGAR EMBASSY KINGS PKT           NaN
4      113128  Tobacco      Cigarettes              CIGAR SM PKT           NaN

#Script that automatically generates the 52 AI image prompts for your taxonomy

In [18]:
subcategories = sorted(final_df['POS_Subcategory'].unique())

print("Total Subcategories:", len(subcategories))
subcategories

Total Subcategories: 52

['Ale',
 'Audio Accessories',
 'Bar Accessories',
 'Bitters',
 'Box Wine',
 'Brandy/Cognac',
 'Chargers & Cables',
 'Cider',
 'Cigarettes',
 'Cigars',
 'Coffee',
 'Confectionery',
 'Dairy',
 'Energy Drink',
 'Fortified Wine',
 'Gin',
 'Hot Beverages',
 'Household',
 'Imported Beer',
 'Juice',
 'Lager',
 'Liqueur',
 'Local Beer',
 'Misc Retail',
 'Mixer/Tonic',
 'Non-Alcoholic Beer',
 'Other Beer',
 'Other Non-Alcoholic',
 'Other Spirits',
 'Other Tobacco',
 'Other Wine',
 'Personal Care',
 'Plant-Based',
 'Ready to Drink (RTD)',
 'Red Wine',
 'Rolling Tobacco',
 'Rosé',
 'Rum',
 'Snacks',
 'Soft Drink',
 'Sparkling/Champagne',
 'Speakers',
 'Sports Drink',
 'Stout/Porter',
 'Tea',
 'Tequila',
 'Vape/E-Cig',
 'Vodka',
 'Water',
 'Wearables',
 'Whiskey',
 'White Wine']

In [19]:
prompts = {}

for sub in subcategories:

    prompt = f"""
Studio product photography of {sub.lower()}, centered product representation,
clean white background, soft shadow, high-end retail catalog style,
minimalistic composition, ultra realistic, 4k, professional lighting
"""

    prompts[sub] = prompt.strip()

prompts

{'Ale': 'Studio product photography of ale, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Audio Accessories': 'Studio product photography of audio accessories, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Bar Accessories': 'Studio product photography of bar accessories, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Bitters': 'Studio product photography of bitters, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Box Wine': 'Studio product photography of box wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Brandy/Cognac': 'Studio product photography of brandy/cognac, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Chargers & Cables': 'Studio product photography of chargers & cables, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cider': 'Studio product photography of cider, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cigarettes': 'Studio product photography of cigarettes, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cigars': 'Studio product photography of cigars, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Coffee': 'Studio product photography of coffee, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Confectionery': 'Studio product photography of confectionery, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Dairy': 'Studio product photography of dairy, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Energy Drink': 'Studio product photography of energy drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Fortified Wine': 'Studio product photography of fortified wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Gin': 'Studio product photography of gin, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Hot Beverages': 'Studio product photography of hot beverages, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Household': 'Studio product photography of household, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Imported Beer': 'Studio product photography of imported beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Juice': 'Studio product photography of juice, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Lager': 'Studio product photography of lager, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Liqueur': 'Studio product photography of liqueur, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Local Beer': 'Studio product photography of local beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Misc Retail': 'Studio product photography of misc retail, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Mixer/Tonic': 'Studio product photography of mixer/tonic, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Non-Alcoholic Beer': 'Studio product photography of non-alcoholic beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Beer': 'Studio product photography of other beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Non-Alcoholic': 'Studio product photography of other non-alcoholic, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Spirits': 'Studio product photography of other spirits, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Tobacco': 'Studio product photography of other tobacco, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Wine': 'Studio product photography of other wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Personal Care': 'Studio product photography of personal care, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Plant-Based': 'Studio product photography of plant-based, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Ready to Drink (RTD)': 'Studio product photography of ready to drink (rtd), centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Red Wine': 'Studio product photography of red wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rolling Tobacco': 'Studio product photography of rolling tobacco, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rosé': 'Studio product photography of rosé, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rum': 'Studio product photography of rum, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Snacks': 'Studio product photography of snacks, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Soft Drink': 'Studio product photography of soft drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Sparkling/Champagne': 'Studio product photography of sparkling/champagne, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Speakers': 'Studio product photography of speakers, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Sports Drink': 'Studio product photography of sports drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Stout/Porter': 'Studio product photography of stout/porter, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Tea': 'Studio product photography of tea, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Tequila': 'Studio product photography of tequila, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Vape/E-Cig': 'Studio product photography of vape/e-cig, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Vodka': 'Studio product photography of vodka, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Water': 'Studio product photography of water, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Wearables': 'Studio product photography of wearables, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Whiskey': 'Studio product photography of whiskey, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'White Wine': 'Studio product photography of white wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting'}

In [20]:
prompt_df = pd.DataFrame({
    "POS_Subcategory": list(prompts.keys()),
    "AI_Image_Prompt": list(prompts.values())
})

prompt_df.head()

     POS_Subcategory                                    AI_Image_Prompt
0                Ale  Studio product photography of ale, centered pr...
1  Audio Accessories  Studio product photography of audio accessorie...
2    Bar Accessories  Studio product photography of bar accessories,...
3            Bitters  Studio product photography of bitters, centere...
4           Box Wine  Studio product photography of box wine, center...

In [21]:
prompt_df.to_csv(
"/content/drive/MyDrive/Dataset/Uzapoint_Taxonomy_Image_Prompts.csv",
index=False
)

In [22]:
image_map = {
    sub: f"https://cdn.uzapoint.com/taxonomy/{sub.lower().replace(' ','_')}.jpg"
    for sub in subcategories
}

missing_mask = final_df['Product Image'].isna()

final_df.loc[missing_mask, 'Product Image'] = final_df.loc[
    missing_mask, 'POS_Subcategory'
].map(image_map)

In [29]:
# ============================================
# UZAPOINT GLOBAL PRODUCT IMAGE GENERATOR (FIXED)
# ============================================

import os
import pandas as pd
import requests
import urllib.parse
from google.colab import drive
import time
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Mount Drive (if not already mounted)
drive.mount('/content/drive')

# ============================================
# STEP 1: LOAD YOUR EXISTING DATA
# ============================================

# Load the final combined dataframe
file_path = '/content/drive/MyDrive/Dataset/Uzapoint_POS_Taxonomy_Base.csv'
combined_df = pd.read_csv(file_path)

# Load the original master data with product images
master_file_path = '/content/drive/MyDrive/Dataset/Uzapoint_Master_Clean_Data.csv'
master_df = pd.read_csv(master_file_path)
image_df = master_df[['Product ID', 'Product Image']].copy()

print("Data loaded successfully!")
print(f"Total products: {len(combined_df)}")
print(f"Total unique subcategories: {combined_df['POS_Subcategory'].nunique()}")
print(f"Total unique categories: {combined_df['Category'].nunique()}")

# ============================================
# STEP 2: CHOOSE YOUR APPROACH
# ============================================

print("\n" + "="*50)
print("CHOOSE YOUR IMAGE GENERATION APPROACH:")
print("="*50)
print("1. Generate images for SUBCATEGORIES (52 images)")
print("2. Generate images for CATEGORIES (6 images)")
print("3. Generate images for BOTH")
print("="*50)

# Set your choice here (change this number)
CHOICE = 1  # Change to 1, 2, or 3

# ============================================
# STEP 3: DEFINE IMAGE GENERATION FUNCTION WITH RETRY LOGIC
# ============================================

def generate_images_with_retry(items, item_type, folder_name, max_retries=3):
    """
    Generate images for a list of items with retry logic for timeouts
    """

    # Create folder in Google Drive
    image_folder = f"/content/drive/MyDrive/{folder_name}"
    os.makedirs(image_folder, exist_ok=True)

    # Setup session with retries
    session = requests.Session()
    retry_strategy = Retry(
        total=2,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504],
    )
    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    print(f"\nGenerating {len(items)} {item_type} images...")
    print("-" * 40)

    # Store image paths/URLs
    image_map = {}
    failed_items = []

    for i, item in enumerate(items, 1):
        # Create filename (sanitize for filesystem)
        filename = item.replace(" ", "_").replace("/", "_").replace("&", "and")
        filename = filename.replace("(", "").replace(")", "").replace("'", "")
        filename = filename + ".jpg"
        filepath = os.path.join(image_folder, filename)

        # Create a descriptive prompt
        if item_type == 'category':
            prompt = f"professional studio photography collage of various {item} products, arranged neatly, clean white background, high-end retail catalog style, 4k quality, multiple products showcase"
        else:
            prompt = f"studio product photography of {item}, centered product representation, clean white background, soft shadow, high-end retail catalog style, minimalistic composition, ultra realistic, 4k, professional lighting"

        # URL encode the prompt
        encoded_prompt = urllib.parse.quote(prompt)

        # Pollinations AI URL
        url = f"https://image.pollinations.ai/prompt/{encoded_prompt}"

        print(f"[{i}/{len(items)}] Generating: {item}")

        # Try to download with retries
        success = False
        for attempt in range(max_retries):
            try:
                # Shorter timeout for first attempt, longer for retries
                timeout = 20 if attempt == 0 else 40
                response = session.get(url, timeout=timeout)

                if response.status_code == 200:
                    with open(filepath, 'wb') as f:
                        f.write(response.content)

                    image_map[item] = {
                        'local_path': filepath,
                        'url': url,
                        'filename': filename,
                        'prompt': prompt
                    }
                    print(f"  ✓ Saved: {filename}")
                    success = True
                    break
                else:
                    print(f"  ⚠ Attempt {attempt + 1}: HTTP {response.status_code}")

            except requests.exceptions.Timeout:
                print(f"  ⚠ Attempt {attempt + 1}: Timeout")
            except requests.exceptions.ConnectionError:
                print(f"  ⚠ Attempt {attempt + 1}: Connection error")
            except Exception as e:
                print(f"  ⚠ Attempt {attempt + 1}: {str(e)[:50]}")

            time.sleep(2)  # Wait before retry

        if not success:
            failed_items.append(item)
            print(f"  ✗ Failed after {max_retries} attempts")

        # Longer delay between different items
        time.sleep(3)

    print(f"\n✓ Completed! {len(image_map)}/{len(items)} images generated")
    if failed_items:
        print(f"✗ Failed items: {', '.join(failed_items[:5])}{'...' if len(failed_items) > 5 else ''}")
    print(f"Images saved to: {image_folder}")

    return image_map, image_folder, failed_items

# ============================================
# STEP 4: GENERATE IMAGES BASED ON CHOICE
# ============================================

all_image_maps = {}
failed_lists = {}

if CHOICE in [1, 3]:
    # Generate subcategory images
    subcategories = sorted(combined_df['POS_Subcategory'].unique())
    sub_map, sub_folder, failed_subs = generate_images_with_retry(
        subcategories, 'subcategory', 'taxonomy_subcategory_images'
    )
    all_image_maps['subcategories'] = sub_map
    failed_lists['subcategories'] = failed_subs

if CHOICE in [2, 3]:
    # Generate category images
    categories = sorted(combined_df['Category'].unique())
    cat_map, cat_folder, failed_cats = generate_images_with_retry(
        categories, 'category', 'taxonomy_category_images'
    )
    all_image_maps['categories'] = cat_map
    failed_lists['categories'] = failed_cats

# ============================================
# STEP 5: CREATE URL MAPPINGS
# ============================================

print("\n" + "="*50)
print("CREATING URL MAPPINGS")
print("="*50)

# Create mapping dictionaries
subcategory_urls = {}
category_urls = {}

if CHOICE in [1, 3]:
    for sub in subcategories:
        if sub in sub_map:
            # Use local file path
            subcategory_urls[sub] = sub_map[sub]['local_path']
        else:
            # For failed ones, create a placeholder or use a default
            subcategory_urls[sub] = "IMAGE_GENERATION_FAILED"

    # Add to dataframe
    combined_df['Generated_Subcategory_Image'] = combined_df['POS_Subcategory'].map(subcategory_urls)
    print(f"✓ Added subcategory image paths to dataframe")

if CHOICE in [2, 3]:
    for cat in categories:
        if cat in cat_map:
            category_urls[cat] = cat_map[cat]['local_path']
        else:
            category_urls[cat] = "IMAGE_GENERATION_FAILED"

    combined_df['Generated_Category_Image'] = combined_df['Category'].map(category_urls)
    print(f"✓ Added category image paths to dataframe")

# ============================================
# STEP 6: HANDLE MISSING PRODUCT IMAGES (FIXED)
# ============================================

print("\n" + "="*50)
print("HANDLING MISSING PRODUCT IMAGES")
print("="*50)

# Merge with original image data
final_df = combined_df.merge(
    image_df,
    on="Product ID",
    how="left"
)

# Check actual column names after merge
print("Columns in final_df:", final_df.columns.tolist())

# Handle missing images based on which images we generated
if CHOICE in [1, 3]:
    # Use subcategory images for missing product images
    missing_mask = final_df['Product Image'].isna()
    final_df.loc[missing_mask, 'Final_Product_Image'] = final_df.loc[missing_mask, 'Generated_Subcategory_Image']
    final_df.loc[~missing_mask, 'Final_Product_Image'] = final_df.loc[~missing_mask, 'Product Image']

    print(f"\nUsing subcategory images to fill missing product images:")
else:
    # Use category images for missing product images
    missing_mask = final_df['Product Image'].isna()
    final_df.loc[missing_mask, 'Final_Product_Image'] = final_df.loc[missing_mask, 'Generated_Category_Image']
    final_df.loc[~missing_mask, 'Final_Product_Image'] = final_df.loc[~missing_mask, 'Product Image']

    print(f"\nUsing category images to fill missing product images:")

# Statistics
total_products = len(final_df)
filled_images = missing_mask.sum()
existing_images = total_products - filled_images

print(f"Total Products: {total_products}")
print(f"Products with original images: {existing_images}")
print(f"Products needing images: {filled_images}")
print(f"Successfully filled: {filled_images - (final_df['Final_Product_Image'] == 'IMAGE_GENERATION_FAILED').sum()}")
print(f"Failed to fill: {(final_df['Final_Product_Image'] == 'IMAGE_GENERATION_FAILED').sum()}")

# ============================================
# STEP 7: SAVE FINAL DATASET
# ============================================

# Keep relevant columns
columns_to_keep = ['Product ID', 'Category', 'POS_Subcategory', 'Product Label',
                   'Product Image', 'Final_Product_Image']
if CHOICE in [1, 3]:
    columns_to_keep.append('Generated_Subcategory_Image')
if CHOICE in [2, 3]:
    columns_to_keep.append('Generated_Category_Image')

final_output = final_df[[col for col in columns_to_keep if col in final_df.columns]]

# Save the final dataset
output_path = "/content/drive/MyDrive/Dataset/Uzapoint_Final_With_Generated_Images.csv"
final_output.to_csv(output_path, index=False)

print(f"\n✓ Final dataset saved to: {output_path}")

# ============================================
# STEP 8: CREATE REFERENCE CSV FOR SUCCESSFUL IMAGES
# ============================================

# Create a reference dataframe for successfully generated images
reference_data = []

if CHOICE in [1, 3]:
    for sub, data in sub_map.items():
        reference_data.append({
            'Type': 'Subcategory',
            'Name': sub,
            'Local_Path': data['local_path'],
            'Filename': data['filename'],
            'Status': 'Success'
        })
    # Add failed ones
    for sub in failed_lists.get('subcategories', []):
        reference_data.append({
            'Type': 'Subcategory',
            'Name': sub,
            'Local_Path': 'FAILED',
            'Filename': sub.replace(" ", "_").replace("/", "_") + ".jpg",
            'Status': 'Failed'
        })

if CHOICE in [2, 3]:
    for cat, data in cat_map.items():
        reference_data.append({
            'Type': 'Category',
            'Name': cat,
            'Local_Path': data['local_path'],
            'Filename': data['filename'],
            'Status': 'Success'
        })
    # Add failed ones
    for cat in failed_lists.get('categories', []):
        reference_data.append({
            'Type': 'Category',
            'Name': cat,
            'Local_Path': 'FAILED',
            'Filename': cat.replace(" ", "_").replace("/", "_") + ".jpg",
            'Status': 'Failed'
        })

if reference_data:
    reference_df = pd.DataFrame(reference_data)
    ref_output_path = "/content/drive/MyDrive/Dataset/Generated_Images_Reference.csv"
    reference_df.to_csv(ref_output_path, index=False)
    print(f"✓ Image reference saved to: {ref_output_path}")

# ============================================
# STEP 9: SUMMARY
# ============================================

print("\n" + "="*50)
print("SUMMARY")
print("="*50)
print(f"Successfully generated images: {len(sub_map) if CHOICE in [1,3] else 0}/{len(subcategories) if CHOICE in [1,3] else 0} subcategories")
if CHOICE in [2,3]:
    print(f"Successfully generated images: {len(cat_map) if CHOICE in [2,3] else 0}/{len(categories)} categories")
print(f"\nFailed items (will need to be retried manually):")
for type_name, failed_list in failed_lists.items():
    if failed_list:
        print(f"{type_name}: {', '.join(failed_list)}")

# ============================================
# OPTIONAL: RETRY FAILED ITEMS
# ============================================

retry_choice = input("\nDo you want to retry failed items now? (yes/no): ")
if retry_choice.lower() == 'yes':
    for type_name, failed_list in failed_lists.items():
        if failed_list:
            print(f"\nRetrying {type_name}...")
            if type_name == 'subcategories':
                new_map, _, new_failed = generate_images_with_retry(
                    failed_list, 'subcategory', 'taxonomy_subcategory_images_retry'
                )
                # Update maps
                sub_map.update(new_map)
                failed_lists[type_name] = new_failed
            elif type_name == 'categories':
                new_map, _, new_failed = generate_images_with_retry(
                    failed_list, 'category', 'taxonomy_category_images_retry'
                )
                cat_map.update(new_map)
                failed_lists[type_name] = new_failed

    print("\nRetry complete! Check the reference CSV for updated status.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Data loaded successfully!
Total products: 47944
Total unique subcategories: 52
Total unique categories: 6

==================================================
CHOOSE YOUR IMAGE GENERATION APPROACH:
==================================================
1. Generate images for SUBCATEGORIES (52 images)
2. Generate images for CATEGORIES (6 images)
3. Generate images for BOTH
==================================================

Generating 52 subcategory images...
----------------------------------------
[1/52] Generating: Ale
  ✓ Saved: Ale.jpg
[2/52] Generating: Audio Accessories
  ✓ Saved: Audio_Accessories.jpg
[3/52] Generating: Bar Accessories
  ✓ Saved: Bar_Accessories.jpg
[4/52] Generating: Bitters

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Bitters%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Bitters.jpg
[5/52] Generating: Box Wine

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Box%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Box%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Box_Wine.jpg
[6/52] Generating: Brandy/Cognac

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Brandy/Cognac%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Brandy/Cognac%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Brandy_Cognac.jpg
[7/52] Generating: Chargers & Cables

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Chargers%20%26%20Cables%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Chargers%20%26%20Cables%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Chargers_and_Cables.jpg
[8/52] Generating: Cider

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cider%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cider%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Cider.jpg
[9/52] Generating: Cigarettes

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cigarettes%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cigarettes%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Cigarettes.jpg
[10/52] Generating: Cigars

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cigars%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Cigars%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Cigars.jpg
[11/52] Generating: Coffee

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Coffee%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Coffee%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Coffee.jpg
[12/52] Generating: Confectionery

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Confectionery%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Confectionery%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Confectionery.jpg
[13/52] Generating: Dairy

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Dairy%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Dairy%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Dairy.jpg
[14/52] Generating: Energy Drink

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Energy%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Energy%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Energy_Drink.jpg
[15/52] Generating: Fortified Wine

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Fortified%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Fortified%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Fortified_Wine.jpg
[16/52] Generating: Gin

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Gin%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Gin%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Gin.jpg
[17/52] Generating: Hot Beverages

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Hot%20Beverages%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Hot%20Beverages%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Hot_Beverages.jpg
[18/52] Generating: Household

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Household%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Household%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Household.jpg
[19/52] Generating: Imported Beer

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Imported%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Imported%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Imported_Beer.jpg
[20/52] Generating: Juice

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Juice%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Juice%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Juice.jpg
[21/52] Generating: Lager

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Lager%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Lager%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Lager.jpg
[22/52] Generating: Liqueur

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Liqueur%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Liqueur%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Liqueur.jpg
[23/52] Generating: Local Beer

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Local%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Local%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Local_Beer.jpg
[24/52] Generating: Misc Retail

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Misc%20Retail%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Misc%20Retail%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Misc_Retail.jpg
[25/52] Generating: Mixer/Tonic

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Mixer/Tonic%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Mixer/Tonic%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Mixer_Tonic.jpg
[26/52] Generating: Non-Alcoholic Beer

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Non-Alcoholic%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Non-Alcoholic%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Non-Alcoholic_Beer.jpg
[27/52] Generating: Other Beer

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Beer%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Other_Beer.jpg
[28/52] Generating: Other Non-Alcoholic

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Non-Alcoholic%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Non-Alcoholic%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Other_Non-Alcoholic.jpg
[29/52] Generating: Other Spirits

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Spirits%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Other_Spirits.jpg
[30/52] Generating: Other Tobacco

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Tobacco%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Tobacco%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Other_Tobacco.jpg
[31/52] Generating: Other Wine

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Other%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Other_Wine.jpg
[32/52] Generating: Personal Care

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Personal%20Care%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Personal%20Care%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Personal_Care.jpg
[33/52] Generating: Plant-Based

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Plant-Based%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Plant-Based%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Plant-Based.jpg
[34/52] Generating: Ready to Drink (RTD)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Ready%20to%20Drink%20%28RTD%29%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Ready%20to%20Drink%20%28RTD%29%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Ready_to_Drink_RTD.jpg
[35/52] Generating: Red Wine

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Red%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Red%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Red_Wine.jpg
[36/52] Generating: Rolling Tobacco

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Rolling%20Tobacco%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Rolling%20Tobacco%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: HTTPSConnectionPool(host='image.pollinations.ai',
  ✓ Saved: Rolling_Tobacco.jpg
[37/52] Generating: Rosé

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Ros%C3%A9%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Ros%C3%A9%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Rosé.jpg
[38/52] Generating: Rum

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Rum%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Rum%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Rum.jpg
[39/52] Generating: Snacks

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Snacks%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Snacks%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Snacks.jpg
[40/52] Generating: Soft Drink

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Soft%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Soft%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Soft_Drink.jpg
[41/52] Generating: Sparkling/Champagne

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Sparkling/Champagne%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Sparkling/Champagne%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Sparkling_Champagne.jpg
[42/52] Generating: Speakers

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Speakers%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Speakers%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Speakers.jpg
[43/52] Generating: Sports Drink

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Sports%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Sports%20Drink%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Sports_Drink.jpg
[44/52] Generating: Stout/Porter

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Stout/Porter%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Stout/Porter%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Stout_Porter.jpg
[45/52] Generating: Tea

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Tea%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Tea%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Tea.jpg
[46/52] Generating: Tequila

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Tequila%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Tequila%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Tequila.jpg
[47/52] Generating: Vape/E-Cig

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Vape/E-Cig%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Vape/E-Cig%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Vape_E-Cig.jpg
[48/52] Generating: Vodka

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Vodka%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Vodka%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Vodka.jpg
[49/52] Generating: Water

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Water%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Water%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Water.jpg
[50/52] Generating: Wearables

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Wearables%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Wearables%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Wearables.jpg
[51/52] Generating: Whiskey

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Whiskey%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20Whiskey%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: Whiskey.jpg
[52/52] Generating: White Wine

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20White%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='image.pollinations.ai', port=443): Read timed out. (read timeout=20)")': /prompt/studio%20product%20photography%20of%20White%20Wine%2C%20centered%20product%20representation%2C%20clean%20white%20background%2C%20soft%20shadow%2C%20high-end%20retail%20catalog%20style%2C%20minimalistic%20composition%2C%20ultra%20realistic%2C%204k%2C%20professional%20lighting

  ⚠ Attempt 1: Connection error
  ✓ Saved: White_Wine.jpg

✓ Completed! 52/52 images generated
Images saved to: /content/drive/MyDrive/taxonomy_subcategory_images

==================================================
CREATING URL MAPPINGS
==================================================
✓ Added subcategory image paths to dataframe

==================================================
HANDLING MISSING PRODUCT IMAGES
==================================================
Columns in final_df: ['Product ID', 'Category', 'POS_Subcategory', 'Product Label', 'Generated_Subcategory_Image', 'Product Image']

Using subcategory images to fill missing product images:
Total Products: 47946
Products with original images: 7977
Products needing images: 39969
Successfully filled: 39969
Failed to fill: 0

✓ Final dataset saved to: /content/drive/MyDrive/Dataset/Uzapoint_Final_With_Generated_Images.csv
✓ Image reference saved to: /content/drive/MyDrive/Dataset/Generated_Images_Reference.csv

==================================================
SUMMARY
==================================================
Successfully generated images: 52/52 subcategories

Failed items (will need to be retried manually):

Do you want to retry failed items now? (yes/no): no