<a href="https://colab.research.google.com/github/Ted-star7/Images/blob/main/Images_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import json
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Load dataset
file_path = '/content/drive/MyDrive/Dataset/Uzapoint_Master_Clean_Data.csv'
df = pd.read_csv(file_path)

# Preview dataset
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Product ID,Product Label,Clean_Product_Label,Category,Subcategory,Parent_Category,Category_norm,Subcategory_norm,Volume,Brand,Product Image,needs_review,has_image,data_quality_score
0,8782,Brown Belt,Brown Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BROWN,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
1,8783,Black Belt,Black Belt,ACCESSORIES,BELTS,Still_Other,accessories,belts,Unknown,BLACK,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
2,8785,Apple Watch 2020,Apple Watch 2020,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
3,8797,Apple Watch 2019,Apple Watch 2019,ACCESSORIES,WATCHES,Still_Other,accessories,watches,Unknown,APPLE,https://uzapointerp.uzahost.com/uploads/produc...,True,True,Needs Review
4,115430,ORAIMO TYPE C DATA CABLE,ORAIMO TYPE C DATA CABLE,ACCESSORIES,PHONE CHARGERS,Still_Other,accessories,phone chargers,Unknown,ORAIMO,NaN,True,False,Needs Review

In [ ]:
image_df = df[['Product ID', 'Product Image']].copy()

image_df.head()

   Product ID                                      Product Image
0        8782  https://uzapointerp.uzahost.com/uploads/produc...
1        8783  https://uzapointerp.uzahost.com/uploads/produc...
2        8785  https://uzapointerp.uzahost.com/uploads/produc...
3        8797  https://uzapointerp.uzahost.com/uploads/produc...
4      115430                                                NaN

In [ ]:
missing_mask = image_df['Product Image'].isna() | (image_df['Product Image'] == "")

missing_count = missing_mask.sum()
total_products = len(image_df)

print("Total Products:", total_products)
print("Missing Images:", missing_count)
print("Existing Images:", total_products - missing_count)

Total Products: 47944
Missing Images: 39967
Existing Images: 7977

In [ ]:
missing_images_df = image_df[missing_mask]

missing_images_df.head()

   Product ID Product Image
4      115430           NaN
5      115431           NaN
6      115432           NaN
7      115433           NaN
8      119107           NaN

In [ ]:
import pandas as pd
import os
from google.colab import drive

drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Dataset/category_review_simple_20260303_195522/category_review_simple_20260303_195522"

import os
files = os.listdir(folder_path)

files

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

['Tobacco_simple.csv',
 'Non-Alcoholic_simple.csv',
 'Wines_simple.csv',
 'Others_simple.csv',
 'Beers_simple.csv',
 'Spirits_simple.csv']

In [ ]:
import pandas as pd
import os

dfs = []

for file in files:

    path = os.path.join(folder_path, file)

    df_temp = pd.read_csv(path)

    dfs.append(df_temp)

combined_df = pd.concat(dfs, ignore_index=True)

combined_df.head()

   Product ID Category POS_Subcategory             Product Label
0      223308  Tobacco      Cigarettes               BIC LIGHTER
1      113125  Tobacco      Cigarettes  CIGAR DUNHILL DOUBLE PKT
2      113126  Tobacco      Cigarettes  CIGAR DUNHILL SINGLE PKT
3      113127  Tobacco      Cigarettes   CIGAR EMBASSY KINGS PKT
4      113128  Tobacco      Cigarettes              CIGAR SM PKT

In [ ]:
print("Total Products:", len(combined_df))

Total Products: 47944

In [ ]:
combined_df['Category'].value_counts()

Category
Spirits          21473
Wines             8502
Others            7556
Non-Alcoholic     5406
Beers             3984
Tobacco           1023
Name: count, dtype: int64

In [ ]:
combined_df.to_csv(
"/content/drive/MyDrive/Dataset/Uzapoint_POS_Taxonomy_Base.csv",
index=False
)

In [ ]:
combined_df['POS_Subcategory'].nunique()

52

In [ ]:
combined_df.columns

Index(['Product ID', 'Category', 'POS_Subcategory', 'Product Label'], dtype='object')

In [ ]:
image_df = image_df[['Product ID', 'Product Image']]

In [ ]:
image_df.head()

   Product ID                                      Product Image
0        8782  https://uzapointerp.uzahost.com/uploads/produc...
1        8783  https://uzapointerp.uzahost.com/uploads/produc...
2        8785  https://uzapointerp.uzahost.com/uploads/produc...
3        8797  https://uzapointerp.uzahost.com/uploads/produc...
4      115430                                                NaN

In [ ]:
final_df = combined_df.merge(
    image_df,
    on="Product ID",
    how="left"
)

final_df.head()

   Product ID Category POS_Subcategory             Product Label Product Image
0      223308  Tobacco      Cigarettes               BIC LIGHTER           NaN
1      113125  Tobacco      Cigarettes  CIGAR DUNHILL DOUBLE PKT           NaN
2      113126  Tobacco      Cigarettes  CIGAR DUNHILL SINGLE PKT           NaN
3      113127  Tobacco      Cigarettes   CIGAR EMBASSY KINGS PKT           NaN
4      113128  Tobacco      Cigarettes              CIGAR SM PKT           NaN

#Script that automatically generates the 52 AI image prompts for your taxonomy

In [ ]:
subcategories = sorted(final_df['POS_Subcategory'].unique())

print("Total Subcategories:", len(subcategories))
subcategories

Total Subcategories: 52

['Ale',
 'Audio Accessories',
 'Bar Accessories',
 'Bitters',
 'Box Wine',
 'Brandy/Cognac',
 'Chargers & Cables',
 'Cider',
 'Cigarettes',
 'Cigars',
 'Coffee',
 'Confectionery',
 'Dairy',
 'Energy Drink',
 'Fortified Wine',
 'Gin',
 'Hot Beverages',
 'Household',
 'Imported Beer',
 'Juice',
 'Lager',
 'Liqueur',
 'Local Beer',
 'Misc Retail',
 'Mixer/Tonic',
 'Non-Alcoholic Beer',
 'Other Beer',
 'Other Non-Alcoholic',
 'Other Spirits',
 'Other Tobacco',
 'Other Wine',
 'Personal Care',
 'Plant-Based',
 'Ready to Drink (RTD)',
 'Red Wine',
 'Rolling Tobacco',
 'Rosé',
 'Rum',
 'Snacks',
 'Soft Drink',
 'Sparkling/Champagne',
 'Speakers',
 'Sports Drink',
 'Stout/Porter',
 'Tea',
 'Tequila',
 'Vape/E-Cig',
 'Vodka',
 'Water',
 'Wearables',
 'Whiskey',
 'White Wine']

In [ ]:
prompts = {}

for sub in subcategories:

    prompt = f"""
Studio product photography of {sub.lower()}, centered product representation,
clean white background, soft shadow, high-end retail catalog style,
minimalistic composition, ultra realistic, 4k, professional lighting
"""

    prompts[sub] = prompt.strip()

prompts

{'Ale': 'Studio product photography of ale, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Audio Accessories': 'Studio product photography of audio accessories, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Bar Accessories': 'Studio product photography of bar accessories, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Bitters': 'Studio product photography of bitters, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Box Wine': 'Studio product photography of box wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Brandy/Cognac': 'Studio product photography of brandy/cognac, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Chargers & Cables': 'Studio product photography of chargers & cables, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cider': 'Studio product photography of cider, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cigarettes': 'Studio product photography of cigarettes, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Cigars': 'Studio product photography of cigars, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Coffee': 'Studio product photography of coffee, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Confectionery': 'Studio product photography of confectionery, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Dairy': 'Studio product photography of dairy, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Energy Drink': 'Studio product photography of energy drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Fortified Wine': 'Studio product photography of fortified wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Gin': 'Studio product photography of gin, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Hot Beverages': 'Studio product photography of hot beverages, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Household': 'Studio product photography of household, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Imported Beer': 'Studio product photography of imported beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Juice': 'Studio product photography of juice, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Lager': 'Studio product photography of lager, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Liqueur': 'Studio product photography of liqueur, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Local Beer': 'Studio product photography of local beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Misc Retail': 'Studio product photography of misc retail, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Mixer/Tonic': 'Studio product photography of mixer/tonic, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Non-Alcoholic Beer': 'Studio product photography of non-alcoholic beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Beer': 'Studio product photography of other beer, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Non-Alcoholic': 'Studio product photography of other non-alcoholic, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Spirits': 'Studio product photography of other spirits, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Tobacco': 'Studio product photography of other tobacco, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Other Wine': 'Studio product photography of other wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Personal Care': 'Studio product photography of personal care, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Plant-Based': 'Studio product photography of plant-based, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Ready to Drink (RTD)': 'Studio product photography of ready to drink (rtd), centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Red Wine': 'Studio product photography of red wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rolling Tobacco': 'Studio product photography of rolling tobacco, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rosé': 'Studio product photography of rosé, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Rum': 'Studio product photography of rum, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Snacks': 'Studio product photography of snacks, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Soft Drink': 'Studio product photography of soft drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Sparkling/Champagne': 'Studio product photography of sparkling/champagne, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Speakers': 'Studio product photography of speakers, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Sports Drink': 'Studio product photography of sports drink, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Stout/Porter': 'Studio product photography of stout/porter, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Tea': 'Studio product photography of tea, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Tequila': 'Studio product photography of tequila, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Vape/E-Cig': 'Studio product photography of vape/e-cig, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Vodka': 'Studio product photography of vodka, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Water': 'Studio product photography of water, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Wearables': 'Studio product photography of wearables, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'Whiskey': 'Studio product photography of whiskey, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting',
 'White Wine': 'Studio product photography of white wine, centered product representation,\nclean white background, soft shadow, high-end retail catalog style,\nminimalistic composition, ultra realistic, 4k, professional lighting'}

In [ ]:
prompt_df = pd.DataFrame({
    "POS_Subcategory": list(prompts.keys()),
    "AI_Image_Prompt": list(prompts.values())
})

prompt_df.head()

     POS_Subcategory                                    AI_Image_Prompt
0                Ale  Studio product photography of ale, centered pr...
1  Audio Accessories  Studio product photography of audio accessorie...
2    Bar Accessories  Studio product photography of bar accessories,...
3            Bitters  Studio product photography of bitters, centere...
4           Box Wine  Studio product photography of box wine, center...

In [ ]:
prompt_df.to_csv(
"/content/drive/MyDrive/Dataset/Uzapoint_Taxonomy_Image_Prompts.csv",
index=False
)

In [ ]:
image_map = {
    sub: f"https://cdn.uzapoint.com/taxonomy/{sub.lower().replace(' ','_')}.jpg"
    for sub in subcategories
}

missing_mask = final_df['Product Image'].isna()

final_df.loc[missing_mask, 'Product Image'] = final_df.loc[
    missing_mask, 'POS_Subcategory'
].map(image_map)

In [ ]:
# ============================================
# UZAPOINT GLOBAL PRODUCT IMAGE GENERATOR
# ============================================

import os
import pandas as pd
import requests
from google.colab import drive

# Mount Drive
drive.mount('/content/drive')

# Folder to store images
image_folder = "/content/drive/MyDrive/taxonomy_images"
os.makedirs(image_folder, exist_ok=True)

# --------------------------------------------
# GET SUBCATEGORIES FROM YOUR DATA
# --------------------------------------------

subcategories = sorted(combined_df["POS_Subcategory"].unique())

print("Total Subcategories:", len(subcategories))
print(subcategories)

# --------------------------------------------
# GENERATE PLACEHOLDER IMAGES USING POLLINATION AI
# --------------------------------------------

image_paths = {}

for sub in subcategories:

    filename = sub.replace(" ", "_").replace("/", "_") + ".jpg"
    filepath = os.path.join(image_folder, filename)

    prompt = f"studio product photo of {sub}, clean white background, professional lighting, ecommerce product photography"

    url = f"https://image.pollinations.ai/prompt/{prompt}"

    try:
        img = requests.get(url).content
        with open(filepath, "wb") as f:
            f.write(img)

        image_paths[sub] = filepath
        print("Saved:", filename)

    except:
        print("Failed:", sub)

print("Image generation complete")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Total Subcategories: 52
['Ale', 'Audio Accessories', 'Bar Accessories', 'Bitters', 'Box Wine', 'Brandy/Cognac', 'Chargers & Cables', 'Cider', 'Cigarettes', 'Cigars', 'Coffee', 'Confectionery', 'Dairy', 'Energy Drink', 'Fortified Wine', 'Gin', 'Hot Beverages', 'Household', 'Imported Beer', 'Juice', 'Lager', 'Liqueur', 'Local Beer', 'Misc Retail', 'Mixer/Tonic', 'Non-Alcoholic Beer', 'Other Beer', 'Other Non-Alcoholic', 'Other Spirits', 'Other Tobacco', 'Other Wine', 'Personal Care', 'Plant-Based', 'Ready to Drink (RTD)', 'Red Wine', 'Rolling Tobacco', 'Rosé', 'Rum', 'Snacks', 'Soft Drink', 'Sparkling/Champagne', 'Speakers', 'Sports Drink', 'Stout/Porter', 'Tea', 'Tequila', 'Vape/E-Cig', 'Vodka', 'Water', 'Wearables', 'Whiskey', 'White Wine']
Saved: Ale.jpg
Saved: Audio_Accessories.jpg
Saved: Bar_Accessories.jpg
Saved: Bitters.jpg
Saved: Box_Wine.jpg
Saved: Brandy_Cognac.jpg
Saved: Chargers_&_Cables.jpg
Saved: Cider.jpg
Saved: Cigarettes.jpg
Saved: Cigars.jpg
Saved: Coffee.jpg
Saved: Confectionery.jpg
Saved: Dairy.jpg
Saved: Energy_Drink.jpg
Saved: Fortified_Wine.jpg
Saved: Gin.jpg
Saved: Hot_Beverages.jpg
Saved: Household.jpg
Saved: Imported_Beer.jpg
Saved: Juice.jpg
Saved: Lager.jpg
Saved: Liqueur.jpg
Saved: Local_Beer.jpg
Saved: Misc_Retail.jpg
Saved: Mixer_Tonic.jpg
Saved: Non-Alcoholic_Beer.jpg
Saved: Other_Beer.jpg
Saved: Other_Non-Alcoholic.jpg
Saved: Other_Spirits.jpg
Saved: Other_Tobacco.jpg
Saved: Other_Wine.jpg
Saved: Personal_Care.jpg
Saved: Plant-Based.jpg
Saved: Ready_to_Drink_(RTD).jpg
Saved: Red_Wine.jpg
Saved: Rolling_Tobacco.jpg
Saved: Rosé.jpg
Saved: Rum.jpg
Saved: Snacks.jpg
Saved: Soft_Drink.jpg
Saved: Sparkling_Champagne.jpg
Saved: Speakers.jpg
Saved: Sports_Drink.jpg
Saved: Stout_Porter.jpg
Saved: Tea.jpg
Saved: Tequila.jpg
Saved: Vape_E-Cig.jpg
Saved: Vodka.jpg
Saved: Water.jpg
Saved: Wearables.jpg
Saved: Whiskey.jpg
Saved: White_Wine.jpg
Image generation complete

In [ ]:
github_base = "https://raw.githubusercontent.com/Ted-star7/product-images/main/images/"

image_map = {}

for sub in subcategories:

    filename = sub.replace(" ", "_").replace("/", "_") + ".jpg"
    image_map[sub] = github_base + filename

print(image_map)

{'Ale': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Ale.jpg', 'Audio Accessories': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Audio_Accessories.jpg', 'Bar Accessories': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Bar_Accessories.jpg', 'Bitters': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Bitters.jpg', 'Box Wine': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Box_Wine.jpg', 'Brandy/Cognac': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Brandy_Cognac.jpg', 'Chargers & Cables': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Chargers_&_Cables.jpg', 'Cider': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Cider.jpg', 'Cigarettes': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Cigarettes.jpg', 'Cigars': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Cigars.jpg', 'Coffee': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Coffee.jpg', 'Confectionery': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Confectionery.jpg', 'Dairy': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Dairy.jpg', 'Energy Drink': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Energy_Drink.jpg', 'Fortified Wine': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Fortified_Wine.jpg', 'Gin': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Gin.jpg', 'Hot Beverages': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Hot_Beverages.jpg', 'Household': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Household.jpg', 'Imported Beer': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Imported_Beer.jpg', 'Juice': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Juice.jpg', 'Lager': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Lager.jpg', 'Liqueur': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Liqueur.jpg', 'Local Beer': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Local_Beer.jpg', 'Misc Retail': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Misc_Retail.jpg', 'Mixer/Tonic': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Mixer_Tonic.jpg', 'Non-Alcoholic Beer': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Non-Alcoholic_Beer.jpg', 'Other Beer': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Other_Beer.jpg', 'Other Non-Alcoholic': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Other_Non-Alcoholic.jpg', 'Other Spirits': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Other_Spirits.jpg', 'Other Tobacco': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Other_Tobacco.jpg', 'Other Wine': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Other_Wine.jpg', 'Personal Care': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Personal_Care.jpg', 'Plant-Based': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Plant-Based.jpg', 'Ready to Drink (RTD)': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Ready_to_Drink_(RTD).jpg', 'Red Wine': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Red_Wine.jpg', 'Rolling Tobacco': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Rolling_Tobacco.jpg', 'Rosé': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Rosé.jpg', 'Rum': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Rum.jpg', 'Snacks': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Snacks.jpg', 'Soft Drink': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Soft_Drink.jpg', 'Sparkling/Champagne': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Sparkling_Champagne.jpg', 'Speakers': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Speakers.jpg', 'Sports Drink': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Sports_Drink.jpg', 'Stout/Porter': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Stout_Porter.jpg', 'Tea': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Tea.jpg', 'Tequila': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Tequila.jpg', 'Vape/E-Cig': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Vape_E-Cig.jpg', 'Vodka': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Vodka.jpg', 'Water': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Water.jpg', 'Wearables': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Wearables.jpg', 'Whiskey': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/Whiskey.jpg', 'White Wine': 'https://raw.githubusercontent.com/Ted-star7/product-images/main/images/White_Wine.jpg'}

In [ ]:
combined_df["Product Image"] = combined_df["POS_Subcategory"].map(image_map)

combined_df.head()

,Product ID,Category,POS_Subcategory,Product Label,Product Image
0,223308,Tobacco,Cigarettes,BIC LIGHTER,https://raw.githubusercontent.com/Ted-star7/pr...
1,113125,Tobacco,Cigarettes,CIGAR DUNHILL DOUBLE PKT,https://raw.githubusercontent.com/Ted-star7/pr...
2,113126,Tobacco,Cigarettes,CIGAR DUNHILL SINGLE PKT,https://raw.githubusercontent.com/Ted-star7/pr...
3,113127,Tobacco,Cigarettes,CIGAR EMBASSY KINGS PKT,https://raw.githubusercontent.com/Ted-star7/pr...
4,113128,Tobacco,Cigarettes,CIGAR SM PKT,https://raw.githubusercontent.com/Ted-star7/pr...

In [ ]:
output_path = "/content/drive/MyDrive/Dataset/Uzapoint_Final_With_Images.csv"

combined_df.to_csv(output_path, index=False)

print("Final dataset saved:", output_path)

Final dataset saved: /content/drive/MyDrive/Dataset/Uzapoint_Final_With_Images.csv